---

# https://podman.io/getting-started/installation.html

- name: platform dependent vars
  include_vars: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/vars/'
  tags: always

- name: establish repo
  include_tasks: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/tasks/establish_repo/'

- name: establish package
  become: true
  package:
    name: podman
    state: present
  tags: install

- name: configure settings
  when: item.use | default(true)
  become: true
  template:
    src: "{{ item.path | default(item) }}.j2"
    dest: "/{{ item.path | default(item) }}"
    owner: root
    group: root
    mode: "u=rw,go=r"
  loop:
    - etc/containers/registries.conf
    - path: etc/containers/storage.conf
      use: "{{ podman_storage is defined }}"
  tags: configure

- name: configure policy
  when: podman_policy is defined
  become: true
  copy:
    content: |
      {{ podman_policy | to_nice_json }}

    dest: /etc/containers/policy.json
    owner: root
    group: root
    mode: "u=rw,go=r"
  tags: configure
