---

- name: Ubuntu | establish prerequisites
  when: ansible_facts['distribution_version'] is version('20.04', '<=')
  become: true
  apt:
    name:
      - gnupg-agent
      - apt-transport-https

- name: Ubuntu | add apt repository key
  when: ansible_facts['distribution_version'] is version('20.04', '<=')
  become: true
  apt_key:
    url: "{{ podman_apt_key_url }}"
    state: present

- name: Ubuntu | add apt repository
  when: ansible_facts['distribution_version'] is version('20.04', '<=')
  become: true
  apt_repository:
    repo: "{{ podman_apt_repository }}"
    filename: podman
