---

- name: Verify
  hosts: all
  tasks:
    - name: podman should be installed
      block:
        - name: check podman version
          command: '/usr/bin/podman --version'
          changed_when: false
          register: r

        - name: assert that podman is installed
          assert:
            that:
              - r.rc == 0
            fail_msg: podman should be installed
